version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container-template
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: template-microservice
    ports:
      - "3306:3306"
    volumes:
      - /Users/lucas/Development/volumes/mysql